name: Go

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.19.4'

    - name: Build
      run: go build -v

    # - name: Test
      # run: go test -v ./...

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: biliroaming-go-server-${{ github.run_number }}
        path: |
          ./biliroaming-go-server
          ./config.yaml
          ./sql/
